#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Initializing application space..."
# Manual creation necessary
ey login <<EOF
$EY_USERNAME
$EY_PASSWORD
EOF

echo "-----> Deploying application..."
# HEAD already deployed after manual creation
# ruby deploy.rb 'HEAD'

# ENV variables
# https://github.com/engineyard/ey-cloud-recipes.git
# copy env config
cp .env recipes/cookbooks/env_vars/attributes/.env > /dev/null || true

cd recipes
ey recipes upload -e $EY_ENVIRONMENT
ey recipes apply -e $EY_ENVIRONMENT
cd ..

echo "-----> Checking availability..."
url=$(ey servers -s -e $EY_ENVIRONMENT | sed -En "s/\s.*$//p")
is_up "http://$url"

