#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Initializing application space..."
# authentication
cf login -u "$PWS_USERNAME" -p "$PWS_PASSWORD" -s "$PWS_SPACE" -a "https://api.run.pivotal.io"

echo "-----> Deploying application..."
# deploy code
cf push $APPNAME -m 512M --no-start

# set env vars
for e in "${evar[@]}"
do
  cf set-env $APPNAME $(echo $e | sed 's/=/ /g')
done

# start app
cf start $APPNAME

# logout
cf logout

echo "-----> Checking availability..."
is_up "https://$APPNAME.cfapps.io"

