#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Initializing application space..."
cf login -u $PWS_USERNAME -p $PWS_PASSWORD -s $PWS_SPACE -a https://api.run.pivotal.io

echo "-----> Deploying application..."
cf push $APPNAME -m 512M --no-start

for e in "${evar[@]}"
do
  cf set-env $APPNAME $(echo $e | sed 's/=/ /g')
done

# options:
# `cf push --no-start`, then `cf set-env` and then `cf start`.
# `cf restart` should only restart the server 
# `cf restage` redeploys completely
# application manifest
cf start $APPNAME

cf logout

echo "-----> Checking availability..."
is_up "https://$APPNAME.cfapps.io"

