#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Updating application..."
cf login -u $PWS_USERNAME -p $PWS_PASSWORD -s $PWS_SPACE -a https://api.run.pivotal.io
cf push $APPNAME
cf logout

echo "-----> Checking availability..."
is_up "https://$APPNAME.cfapps.io"

