#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Removing application..."
cf login -u $BM_USERNAME -p $BM_PASSWORD -s $BM_SPACE -a https://api.ng.bluemix.net
cf delete $APPNAME -f -r

echo "-----> Cleaning application space..."
cf logout

echo "-----> Checking availability..."
is_down "https://$APPNAME.mybluemix.net"

