#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Updating application..."
cf login -u "$BM_USERNAME" -p "$BM_PASSWORD" -s "$BM_SPACE" -a "https://api.ng.bluemix.net"
cf push $APPNAME
cf logout

echo "-----> Checking availability..."
is_up "https://$APPNAME.mybluemix.net"

