#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Updating application..."
# --deploy immediately deploys after push
expect <<'END'
  set timeout 1000
  spawn dcapp $env(APPNAME)/default push --deploy
  expect {
    -re "Email.*" { send "$env(DC_USERNAME)\r"; exp_continue } 
    -re ".*Password.*" { send "$env(DC_PASSWORD)\r"; exp_continue }
    -re ".*continue connecting (yes/no)?" { send "yes\r"}
  }
END

# deletes token
dcuser logout

echo "-----> Checking availability..."
is_up "https://$APPNAME.dotcloudapp.com"

