#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Removing application..."
# authentication
heroku auth:login <<END
$HEROKU_USERNAME
$HEROKU_PASSWORD
END

# delete app
heroku apps:destroy --app $APPNAME --confirm $APPNAME

echo "-----> Cleaning application space..."
# ssh keys
heroku keys:remove dploy
# delete tokens
heroku auth:logout

echo "-----> Checking availability..."
is_down "https://$APPNAME.herokuapp.com"

