#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Initializing application space..."
# authentication
heroku auth:login <<END
$HEROKU_USERNAME
$HEROKU_PASSWORD
END

# create app space
heroku create $APPNAME

# set env vars
if [[ !${#evar[@]} -eq 0 ]]; then
  heroku config:set ${evar[@]}
fi

echo "-----> Deploying application..."
expect <<'END'
  set timeout 1000
  spawn git push heroku master
  expect {
    -re ".*continue connecting (yes/no)?" { send "yes\r" }
  }
  expect eof
END

echo "-----> Checking availability..."
is_up "https://$APPNAME.herokuapp.com"

