#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Updating application..."
# authentication
heroku auth:login <<END
$HEROKU_USERNAME
$HEROKU_PASSWORD
END

# add remote if missing
git remote remove heroku || true
heroku git:remote -a $APPNAME

# update files
git push heroku master -f

echo "-----> Checking availability..."
is_up "https://$APPNAME.herokuapp.com"

