#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Updating application..."
# add remote if missing
heroku git:remote -a $APPNAME
# update files
spawn git push heroku master

echo "-----> Checking availability..."
is_up "https://$APPNAME.herokuapp.com"

