#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Removing application..."
# reconfigure app
ruby set_appname.rb

# region (default: us-east)
expect <<'END'
  set timeout -1
  spawn eb init
  expect {
    -re ".*default region.*" { send "1\r" }
  }
  expect eof
END

eb terminate --all --force

echo "-----> Checking availability..."
url=$(eb status | sed -En "s/CNAME.*?: (.*)$/\1/p")
is_down $url
