#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Initializing application space..."
. eb_init.sh

echo "-----> Deploying application..."
eb start --verbose <<EOF
y
EOF

# WORKAROUND --polling-timeout 1800 is bugged
# see https://forums.aws.amazon.com/message.jspa?messageID=562409#562409
# wait for instance to be ready
printf "Waiting for instance to be ready again"

until [ "$(eb status | sed -En "s/Status.*?: (.*)$/\1/p")" == "Ready" ]; do
  printf "."
  sleep 1
done

printf "\n"

echo "-----> Checking availability..."
url=$(eb status | sed -En "s/URL.*?: (.*)$/\1/p")
is_up $url

