#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Initializing application space..."
# 1-3. api, user, pass
# 4. login token for this session
# 5. upload ssh key
# 6. ssh key name or default if none present
rhc setup <<EOF

$OS_USERNAME
$OS_PASSWORD
yes
yes
dploy
EOF

# -s for scalable, --gear-size small.highcpu
expect <<'END'
  set timeout 1000
  spawn rhc create-app $env(APPNAME) ruby-2.0 --no-git
  expect eof
END

if [[ !${#evar[@]} -eq 0 ]]; then
  rhc set-env BUNDLE_WITHOUT="development:test" ${evar[@]} --app $APPNAME
fi

echo "-----> Deploying application..."
git=$(rhc show-app $APPNAME | sed -En "s/Git URL:(.*)$/\1/p")
git remote remove openshift || true
git remote add openshift $git
expect <<'END'
  set timeout -1
  spawn git push -f openshift master
  expect {
    -re ".*continue connecting (yes/no)?" { send "yes\r" }
  }
  expect eof
END

# auth token
rhc logout

echo "-----> Checking availability..."
is_up "https://$APPNAME-$OS_DOMAIN.rhcloud.com"

