#!/bin/bash
set -eo pipefail

_DIR_="$(dirname "$0")"
cd $_DIR_

. helpers.sh

echo "-----> Updating application..."
git=$(rhc show-app $APPNAME -l $OS_USERNAME -p $OS_PASSWORD | sed -En "s/Git URL:(.*)$/\1/p")
git remote add openshift $git
expect <<'END'
  set timeout -1
  spawn git push -f openshift master
  expect {
    -re ".*continue connecting (yes/no)?" { send "yes\r" }
  }
  expect eof
END
# auth token
rhc logout

echo "-----> Checking availability..."
is_up "https://$APPNAME-$OS_DOMAIN.rhcloud.com"

